import unittest
from adaptive_engine import *
SAFE=SnapshotAuthority(True,2,True,True,True)
def cand(key,conf=Confidence.HIGH,clickable=True,unique=True,margin=True,fresh=True): return Candidate(key,conf,clickable,unique,margin,fresh)
class T(unittest.TestCase):
 def setUp(self): self.e=AdaptiveAutopilot()
 def o(self,**kw):
  d=dict(android_api=34,oem='Samsung',accessibility_enabled=True,authority=SAFE); d.update(kw); return Observation(**d)
 def test_01_done(self): self.assertEqual(self.e.decide(self.o(support_connected=True)).action,Action.DONE)
 def test_02_adb_shortcut(self): self.assertEqual(self.e.decide(self.o(adb_connected=True)).action,Action.CONNECT_SUPPORT)
 def test_03_old_android(self): self.assertEqual(self.e.decide(self.o(android_api=29)).action,Action.UNSUPPORTED_ANDROID)
 def test_04_accessibility(self): self.assertEqual(self.e.decide(self.o(accessibility_enabled=False)).action,Action.ASK_ENABLE_ACCESSIBILITY)
 def test_05_fast_probe(self): self.assertEqual(self.e.decide(self.o(screen=Screen.APP)).action,Action.OPEN_DEVELOPER_SETTINGS)
 def test_06_samsung_fallback(self): self.assertEqual(self.e.decide(self.o(screen=Screen.SETTINGS_HOME,direct_dev_probe_attempted=True)).action,Action.OPEN_DEVICE_INFO_SETTINGS)
 def test_07_other_oem_fallback(self): self.assertEqual(self.e.decide(self.o(oem='Xiaomi',screen=Screen.SETTINGS_HOME,direct_dev_probe_attempted=True)).action,Action.FALLBACK_GUIDE)
 def test_08_about(self): self.assertEqual(self.e.decide(self.o(screen=Screen.ABOUT_PHONE,candidate=cand('software_info'))).action,Action.CLICK_SOFTWARE_INFO)
 def test_09_build(self): self.assertEqual(self.e.decide(self.o(screen=Screen.SOFTWARE_INFO,candidate=cand('build_number'))).action,Action.CLICK_BUILD_NUMBER)
 def test_10_each_build_tap(self):
  for n in range(7): self.assertEqual(self.e.decide(self.o(screen=Screen.SOFTWARE_INFO,candidate=cand('build_number'),build_taps_done=n)).action,Action.CLICK_BUILD_NUMBER)
 def test_11_after_7(self): self.assertEqual(self.e.decide(self.o(screen=Screen.SOFTWARE_INFO,candidate=cand('build_number'),build_taps_done=7)).action,Action.OPEN_DEVELOPER_SETTINGS)
 def test_12_credential(self): self.assertEqual(self.e.decide(self.o(screen=Screen.CREDENTIAL_PROMPT)).action,Action.WAIT_USER_CREDENTIAL)
 def test_13_dev(self): self.assertEqual(self.e.decide(self.o(screen=Screen.DEVELOPER_OPTIONS,candidate=cand('wireless_debugging'))).action,Action.CLICK_WIRELESS_DEBUGGING)
 def test_14_wireless_off(self): self.assertEqual(self.e.decide(self.o(screen=Screen.WIRELESS_DEBUGGING,candidate=cand('wireless_debugging_toggle'),wireless_enabled=False)).action,Action.ENABLE_WIRELESS_DEBUGGING)
 def test_15_wireless_on(self): self.assertEqual(self.e.decide(self.o(screen=Screen.WIRELESS_DEBUGGING,candidate=cand('pair_with_code'),wireless_enabled=True)).action,Action.CLICK_PAIR_WITH_CODE)
 def test_16_network(self): self.assertEqual(self.e.decide(self.o(screen=Screen.NETWORK_CONFIRMATION,candidate=cand('network_confirm_positive'))).action,Action.ACCEPT_NETWORK_CONFIRMATION)
 def test_17_pair_auto(self): self.assertEqual(self.e.decide(self.o(screen=Screen.PAIRING_DIALOG,pair_code_candidates=('123456',),pairing_context_high=True)).action,Action.AUTO_PAIR_WITH_CODE)
 def test_18_pair_multi(self): self.assertEqual(self.e.decide(self.o(screen=Screen.PAIRING_DIALOG,pair_code_candidates=('123456','654321'),pairing_context_high=True)).action,Action.SHOW_MANUAL_PAIR_CODE)
 def test_19_pair_context(self): self.assertEqual(self.e.decide(self.o(screen=Screen.PAIRING_DIALOG,pair_code_candidates=('123456',),pairing_context_high=False)).action,Action.SHOW_MANUAL_PAIR_CODE)
 def test_20_pair_request(self): self.assertEqual(self.e.decide(self.o(screen=Screen.PAIRING_DIALOG,pair_code_candidates=('123456',),pairing_context_high=True,request_active=False)).action,Action.SHOW_MANUAL_PAIR_CODE)
 def assertUnsafe(self,auth=None,candidate=None): self.assertEqual(self.e.decide(self.o(screen=Screen.ABOUT_PHONE,authority=auth or SAFE,candidate=candidate or cand('software_info'))).action,Action.FALLBACK_GUIDE)
 def test_21_unstable(self): self.assertUnsafe(SnapshotAuthority(True,1,True,True,True))
 def test_22_wrong_window(self): self.assertUnsafe(SnapshotAuthority(False,2,True,True,True))
 def test_23_ambiguous(self): self.assertUnsafe(SnapshotAuthority(True,2,True,True,True,True))
 def test_24_generation(self): self.assertUnsafe(SnapshotAuthority(True,2,False,True,True))
 def test_25_windowid(self): self.assertUnsafe(SnapshotAuthority(True,2,True,False,True))
 def test_26_fingerprint(self): self.assertUnsafe(SnapshotAuthority(True,2,True,True,False))
 def test_27_medium(self): self.assertUnsafe(candidate=cand('software_info',conf=Confidence.MEDIUM))
 def test_28_not_unique(self): self.assertUnsafe(candidate=cand('software_info',unique=False))
 def test_29_margin(self): self.assertUnsafe(candidate=cand('software_info',margin=False))
 def test_30_fresh(self): self.assertUnsafe(candidate=cand('software_info',fresh=False))
 def test_31_clickable(self): self.assertUnsafe(candidate=cand('software_info',clickable=False))
 def test_32_wireless_unknown(self): self.assertEqual(self.e.decide(self.o(screen=Screen.WIRELESS_DEBUGGING,candidate=cand('pair_with_code'))).action,Action.WAIT_STABLE)
 def test_33_pair_unstable(self): self.assertEqual(self.e.decide(self.o(screen=Screen.PAIRING_DIALOG,authority=SnapshotAuthority(True,1,True,True,True),pair_code_candidates=('123456',),pairing_context_high=True)).action,Action.WAIT_STABLE)
if __name__=='__main__': unittest.main()
