import { useState } from "react";
import { LabStateKey, labScenarios } from "./labState";

const userScreens = ["Inicio", "Mis apps", "Internet", "Ajustes", "Solicitudes", "Avisos", "Protección", "Actualizaciones", "Datos de contacto", "Tu opinión", "Ayuda"];
const stateOptions: [LabStateKey, string][] = [["connectedProtected", "Normal"], ["loading", "Loading"], ["empty", "Empty"], ["error", "Error"]];

function MockContent({ screen, state }: { screen: string; state: ReturnType<typeof getState> }) {
  if (state.loading) return <div className="state-page centered"><div className="skeleton hero-skeleton" /><div className="skeleton line wide" /><div className="skeleton line" /><p>Sincronizando una vista de prueba…</p></div>;
  if (state.error) return <div className="state-page centered"><div className="state-illustration error">!</div><h3>Algo no salió bien</h3><p>{state.error}</p><button className="primary">Reintentar</button></div>;
  if (state.isEmpty) return <div className="state-page centered"><div className="state-illustration empty">＋</div><h3>Conectá tu dispositivo</h3><p>Esta vista usa datos mock para revisar el diseño antes de conectar servicios reales.</p><button className="primary">Empezar</button></div>;
  const title = screen === "Inicio" ? "Todo está bien" : screen;
  return <div className="app-content"><div className="protection-hero"><div className="hero-orbit"><span className="icon">✓</span></div><p className="eyebrow">Estado general</p><h1>{title}</h1><p>Glosh está protegiendo tu dispositivo.</p><span className="live-pill"><i />Conectado y protegido</span></div><h3 className="section-heading">Resumen</h3><div className="user-summary"><article><div><small>Dispositivo</small><strong>Samsung S22</strong></div></article><article><div><small>Licencia</small><strong>Plan familiar</strong></div></article></div><div className="detail-card"><div><span>Estado</span><strong className="success-text">Activo</strong></div><div><span>Última sincronización</span><strong>hace 8 s</strong></div><div><span>Reglas aplicadas</span><strong>12</strong></div></div><button className="primary full">Ver estado de protección</button></div>;
}
function getState(key: LabStateKey) { return labScenarios[key]; }

export function App() {
  const [screen, setScreen] = useState(0); const [stateKey, setStateKey] = useState<LabStateKey>("connectedProtected"); const state = getState(stateKey);
  return <div className="lab"><header className="lab-bar"><div className="lab-brand"><span className="brand-mark">G</span><span><strong>Glosh</strong><small>App Usuario · UI Lab</small></span></div><div className="app-switch"><button className="selected">App Usuario</button></div><div className="state-switch">{stateOptions.map(([id, label]) => <button key={id} className={stateKey === id ? "selected" : ""} onClick={() => setStateKey(id)}><i className={`state-dot ${id === "connectedProtected" ? "normal" : id}`} />{label}</button>)}</div></header><main className="lab-stage"><aside className="screen-picker"><p className="eyebrow">Laboratorio visual</p><h1>App Usuario</h1><p className="picker-copy">Mismas secciones de la app real, representadas con datos mock.</p><nav>{userScreens.map((item, i) => <button key={item} className={screen === i ? "selected" : ""} onClick={() => setScreen(i)}><span>◉</span><span>{item}</span><span>›</span></button>)}</nav><div className="lab-note">✦<p><strong>V2 visual</strong><span>Mock navegable para iterar UI/UX antes de llevar decisiones a Android.</span></p></div></aside><section className="device-area"><div className="preview-caption"><span><i />Vista previa interactiva</span><span>Android · Responsive</span></div><div className="phone-frame"><div className="phone-speaker" /><div className="phone-screen"><div className="system-bar"><span>9:41</span><span>⌁ ▰</span></div><div className="app-page"><header className="app-header"><span className="mini-brand">G</span><div><h2>Glosh</h2><small>Protección simple para tu familia</small></div><button className="icon-button header-action">⋯</button></header><div className="app-scroll"><MockContent screen={userScreens[screen]} state={state} /></div><nav className="bottom-nav">{userScreens.slice(0, 4).map((item, i) => <button key={item} className={screen === i ? "active" : ""} onClick={() => setScreen(i)}><span className="icon">◉</span>{item}</button>)}</nav></div></div></div></section></main></div>;
}
